### ISSUE TITLE
Branch for Raspberry Pi

### ISSUE THREAD

**Issue by stiucsib86** [privcycoin/privcy#1]
I have a branch with fixes for Raspberry Pi build: https://github.com/stiucsib86/privcy/tree/raspberry. 

How can I request for a "raspberry" branch to be created on the repo in order for me to submit pull request?

**Comment by privcycoin** [comment]
Branch has been setup, thank you.

**Comment by Dev197** [comment]
Was this ever ever supplied or merged?
